default_platform(:android)

platform :android do
  desc "Upload metadata and images to Google Play"
  lane :upload_metadata do
    supply(
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_changelogs: true,
      validate_only: false
    )
  end

  desc "Build and upload a new Internal Build"
  lane :beta do
    gradle(task: "clean :composeApp:bundleRelease")
    upload_to_play_store(
      track: 'internal',
      aab: 'composeApp/build/outputs/bundle/release/composeApp-release.aab'
    )
  end
end
